name: Cross-platform Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_on_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run quick tests
      run: pytest .\test\test_main.py

  test_on_windows:
  
      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run quick tests
        run: pytest .\test\test_main.py

  